### ISSUE TITLE
使用tun模式时电脑开移动热点会导致电脑无法联网

### ISSUE THREAD

**Issue by Lee-cybererwgft** [Fndroid/clash_for_windows_pkg#1728] opened 2021-03-23 16:12 UTC
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[/Windows 10 Home 64-bit operating system, x64-based processor/]: # (平台及版本号)

**描述**

[/使用tun模式时电脑开移动热点会导致电脑无法联网,之前使用tap模式时则无此问题/]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[/time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50705 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50703 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50708 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50709 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50710 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50714 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50711 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50712 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50713 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50715 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50716 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50717 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50718 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50720 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50721 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50719 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50722 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50723 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50724 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50725 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50726 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50729 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50730 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50727 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50728 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50731 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50733 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50737 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50732 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50734 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50735 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50736 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50738 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50739 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50740 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50741 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50743 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50744 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50742 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50745 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50746 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50747 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50749 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50748 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50751 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50750 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50752 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50754 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50753 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50756 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50757 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50755 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50758 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50759 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50760 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50761 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50764 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50762 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50763 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50766 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50765 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50768 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50767 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50769 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50770 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50771 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50773 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50772 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50774 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50777 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50775 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50776 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50778 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50780 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50779 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50781 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50784 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50782 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50783 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50785 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50787 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50786 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50788 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50790 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50789 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50792 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50791 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50794 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50795 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50793 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50797 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50800 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50799 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50796 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50798 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50802 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50801 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50803 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50804 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50805 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50806 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50807 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50809 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50808 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50812 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50810 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50814 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50813 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50811 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50815 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50816 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50817 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50818 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50821 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50820 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50823 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50822 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50819 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50824 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50825 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50826 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50828 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50829 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50830 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50827 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50831 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50832 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50834 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50836 --> 1.2.4.8 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50833 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50835 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50837 --> 114.114.114.114 match GeoIP(CN) using DIRECT"
time="2021-03-23T23:48:59+08:00" level=info msg="[UDP] 192.168.0.103:50838 --> 1.2.4.8 match GeoIP(CN) using DIRECT"/]: # (上传触发问题对应的日志文件)

**截图**

[/https://img.maocdn.cn/img/2021/03/24/Screenshot-2021-03-23-235506.png/]: # (如果可以，请提供对应问题的截图)

**其他说明**

[/顺便请问一下现在CFW支持哪些协议呢，支持VLESS, Xray，或者Trojan-go吗？/]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment] 2021-03-23 23:51
Duplicate of #1444

**Comment by Lee-cybererwgft** [comment] 2021-03-24 04:32
明白了，谢谢大佬，顺便请问下现在CFW支持哪些协议呢，是否支持trojan-go 和Xray或者Vless呢？

**Comment by yi-Xu-0100** [comment] 2021-03-24 04:48
@Lee-cybererwgft <https://github.com/Dreamacro/clash/wiki/configuration#all-configuration-options> 看看 proxies 支持的字段

**Comment by Lee-cybererwgft** [comment] 2021-03-29 13:59
还有一个疑问想请教一下大佬，最近在自己尝试写配置文件，能大致说下配置文件里负载均衡中 strategy: consistent-hashing # or round-robin两种选项有什么区别吗？

**Comment by yi-Xu-0100** [comment] 2021-03-30 00:00
@Lee-cybererwgft https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/load-balance

非官方 wiki ，但是官方推荐阅读的，可以参考

**Comment by Lee-cybererwgft** [comment] 2021-03-30 13:32
特意查了下一致性哈希算法和轮询调度算法，还是有点不太明白，那一般推荐用哪种算法，或者是不设置strategy呢？

**Comment by yi-Xu-0100** [comment] 2021-03-30 13:35
@Lee-cybererwgft 我不知道，我不用这个 `load-balance` 模式

**Comment by Lee-cybererwgft** [comment] 2021-03-30 15:01
终于自己完成了配置文件，谢谢两位大佬的帮助！

**Closed** 2021-03-30 23:09 UTC
