### ISSUE TITLE
Automatically updates subscriptions after opening the app

### ISSUE THREAD

**Issue by zhouzl7** [Fndroid/clash_for_windows_pkg#632] opened 2020-04-10 10:27 UTC
**描述**
Automatically updates subscriptions every time opening the app, hope you can add a button for each subscription profile to implement this function.

**其他说明**
其他补充内容

**Comment by hyq3351** [comment] 2020-04-10 11:34
Duplicate of #584

**Closed** 2020-04-10 12:31 UTC
Labels: no plan
