### ISSUE TITLE
通过clash托管链接添加Profiles报错

### ISSUE THREAD

**Issue by btcforver** [Fndroid/clash_for_windows_pkg#391] opened 2020-01-23 04:18 UTC
![image](https://user-images.githubusercontent.com/60208053/72956335-52d3d280-3dda-11ea-87e6-ea9ad4e44b8f.png)
提示：cipher not supported
请问是啥原因？

**Comment by Fndroid** [comment] 2020-01-23 04:20
Duplicate of #323

**Closed by Fndroid** 2020-01-23 04:20 UTC
