### ISSUE TITLE
开关System Proxy时候都会报错

### ISSUE THREAD

**Issue by 12401010313** [Fndroid/clash_for_windows_pkg#450] opened 2020-02-25 03:15 UTC
Cannot set system proxy
ReferenceError: __static is not defind ....
![QQ截图20200225111514](https://user-images.githubusercontent.com/9304931/75211823-212a9e80-57c0-11ea-8cb1-2c2fb3db9a06.png)

**Comment by Fndroid** [comment] 2020-02-25 03:18
Duplicate of #416

**Closed by Fndroid** 2020-02-25 03:18 UTC
